"use client";

import { VisionDocument } from "@/types/interview";

interface DocumentPreviewProps {
  document: VisionDocument;
  onContinue: () => void;
}

const SECTION_LABELS: Record<keyof VisionDocument, string> = {
  problemStatement: "Problem Statement",
  vision: "Vision",
  targetUsers: "Target Users",
  userNeeds: "User Needs",
  solutionOverview: "Solution Overview",
  businessModel: "Business Model",
  successMetrics: "Success Metrics",
};

export default function DocumentPreview({
  document,
  onContinue,
}: DocumentPreviewProps) {
  const keys = Object.keys(SECTION_LABELS) as (keyof VisionDocument)[];
  const visibleKeys = keys.slice(0, 3);
  const blurredKeys = keys.slice(3);

  return (
    <div className="relative w-full">
      <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-8">
        <h2 className="text-2xl font-bold text-[#1E2429] mb-1">
          Product Vision Document
        </h2>
        <p className="text-sm text-gray-400 mb-8">
          Generated by AICofounder · A free tool by Applitude
        </p>

        {/* Visible sections */}
        {visibleKeys.map((key) => (
          <div key={key} className="mb-8">
            <h3 className="text-xs font-semibold uppercase tracking-widest text-gray-400 mb-2">
              {SECTION_LABELS[key]}
            </h3>
            <p className="text-[#1E2429] leading-relaxed text-sm whitespace-pre-line">
              {document[key]}
            </p>
          </div>
        ))}

        {/* Blurred sections */}
        <div className="relative">
          <div className="blur-sm select-none pointer-events-none">
            {blurredKeys.map((key) => (
              <div key={key} className="mb-8">
                <h3 className="text-xs font-semibold uppercase tracking-widest text-gray-400 mb-2">
                  {SECTION_LABELS[key]}
                </h3>
                <p className="text-[#1E2429] leading-relaxed text-sm whitespace-pre-line">
                  {document[key]}
                </p>
              </div>
            ))}
          </div>

          {/* Overlay CTA */}
          <div className="absolute inset-0 flex flex-col items-center justify-center bg-gradient-to-t from-white via-white/80 to-transparent rounded-b-2xl">
            <div className="text-center px-6">
              <p className="text-[#1E2429] font-semibold text-lg mb-2">
                Your document is ready.
              </p>
              <p className="text-gray-500 text-sm mb-6">
                Enter your email to receive the full PDF.
              </p>
              <button
                onClick={onContinue}
                className="px-8 py-3 bg-[#DBF227] text-[#1E2429] font-bold rounded-xl hover:bg-[#cde020] transition"
              >
                Get the full PDF →
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
